core/urls.py
from django.urls import path
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import url

from django.views.static import serve

from .views import (
    ItemDetailView,
    CheckoutView,
    # HomeView,
    OrderSummaryView,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
    # PaymentView,
    AddCouponView,
    ShopCreate,
    MarketsView,
    ShopsView,
    ProductsView,
    get_items,
    # RequestRefundView,
    add_item, add_shop,
    CustomerOrderStatusView,
    get_shop_cat_items,
    home_view,
    side_bar,
    get_shops,

)
app_name = 'core'

urlpatterns = [
    # path('all', HomeView.as_view(), name='home'),
    # path('', ShopsView.as_view(), name='shops'),
    # path('', home_view, name='home'),
    path('', MarketsView.as_view(), name='markets'),
    path('markets/', MarketsView.as_view(), name='markets'),
    path('shops/', ShopsView.as_view(), name='shops'),
    path('products/', ProductsView.as_view(), name='products'),

    path('shop-items/<id>/', get_items, name='shop-items'),
    path('area/<id>/', get_shops, name='area-shops'),
    path('shops-cat/<id>', get_shop_cat_items,
         name='shops-cat'),
    path('offer-shop/<id>', get_shop_cat_items,
         name='shops-offer'),

    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('shop/add/', ShopCreate.as_view(), name='add-shop'),
    path('order/', CustomerOrderStatusView.as_view(), name='customer-order'),

    # path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    # path('request-refund/', RequestRefundView.as_view(), name='request-refund'),
    url(r'^uploads/simple/$', add_shop, name='add_shop'),
    url(r'^uploads/form/$', add_item, name='add_item'),
    url(r'^image/(?P<path>.*)$', serve,
        {'document_root': settings.MEDIA_ROOT}),

    url(r'^static/(?P<path>.*)$', serve,
        {'document_root': settings.STATIC_ROOT}),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

home/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core'))
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <!-- Title  -->
    <title>{% block head_title %}{% endblock %}</title>
    <!-- Favicon  -->
    <link rel="icon" href="{% static 'user/img/core-img/favicon.ico' %}">

    <!-- Core Style CSS -->
    <link rel="stylesheet" href="{% static 'user/css/core-style.css' %}">
    <link rel="stylesheet" href="{% static 'user/style.css' %}">

    <!-- bootstarp -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">


</head>



<body>
    {% block search %}
    <div class="md-form active-pink active-pink-2 mb-3 mt-1">

        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="search-content">

                        <form action="#" method="get">
                            <input class="form-control" name="search" id="search">


                        </form>

                    </div>

                </div>
            </div>
        </div>
    </div>
    {% endblock search %}
    {% block content %}
    {% endblock content %}

    {% block extra_body %}
    {% endblock %}

    {% include "footer.html" %}
    {% include "scripts.html" %}

    {% block extra_scripts %}
    {% endblock extra_scripts %}

    <script>

        // Add something to given element placeholder
        function addToPlaceholder(toAdd, el) {
            el.attr('placeholder', el.attr('placeholder') + toAdd);
            // Delay between symbols "typing" 
            return new Promise(resolve => setTimeout(resolve, 100));
        }

        // Cleare placeholder attribute in given element
        function clearPlaceholder(el) {
            el.attr("placeholder", "");
        }

        // Print one phrase
        function printPhrase(phrase, el) {
            return new Promise(resolve => {
                // Clear placeholder before typing next phrase
                clearPlaceholder(el);
                let letters = phrase.split('');
                // For each letter in phrase
                letters.reduce(
                    (promise, letter, index) => promise.then(_ => {
                        // Resolve promise when all letters are typed
                        if (index === letters.length - 1) {
                            // Delay before start next phrase "typing"
                            setTimeout(resolve, 1000);
                        }
                        return addToPlaceholder(letter, el);
                    }),
                    Promise.resolve()
                );
            });
        }

        // Print given phrases to element
        function printPhrases(phrases, el) {
            // For each phrase
            // wait for phrase to be typed
            // before start typing next
            phrases.reduce(
                (promise, phrase) => promise.then(_ => printPhrase(phrase, el)),
                Promise.resolve()
            );
        }

        // Start typing


        (function run() {
            let phrases = [
                "আপনার আশেপাশের পছন্দের সব শপিং মল বা সেবা খুজুন ",
                "আপনার পছন্দের শপ খুজুন ",
                "পছন্দের পণ্য খুজুন ",
                "নতুন : জলিল টাওয়ারের পণ্য খুজুন "

            ];

            printPhrases(phrases, $('#search'));
            setTimeout(run, 15000);

        })();



    // setInterval(function () { H alert("ello") }, 3000);
        /*
            // create 1 second interval with immediate execution
            var myInterval = setIntervalImmediately(_ => {
                let phrases = [
                    "আপনার আশেপাশের পছন্দের সব শপিং মল বা সেবা খুজুন ",
                    "আপনার পছন্দের শপ খুজুন ",
                    "পছন্দের পণ্য খুজুন ",
                    "নতুন : জলিল টাওয়ারের পণ্য খুজুন "

                ];

                printPhrases(phrases, $('#search'));
            }, 1000);

            // clear interval after 4.5 seconds
            setTimeout(_ => {
                clearInterval(myInterval);
            }, 4500);

        */

    </script>

</body>

</html>

templates/base1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="au theme template">
    <meta name="author" content="Hau Nguyen">
    <meta name="keywords" content="au theme template">

    <!-- Title Page-->
    <title>{% block head_title %}{% endblock %}</title>

    <!-- Fontfaces CSS-->
    <link href="{% static 'shop/css/font-face.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'shop/vendor/font-awesome-4.7/css/font-awesome.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'shop/vendor/font-awesome-5/css/fontawesome-all.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'shop/vendor/mdi-font/css/material-design-iconic-font.min.css' %}" rel="stylesheet"
        media="all">

    <!-- Bootstrap CSS-->
    <link href="{% static 'shop/vendor/bootstrap-4.1/bootstrap.min.css' %}" rel="stylesheet" media="all">

    <!-- Vendor CSS-->
    <link href="{% static 'shop/vendor/animsition/animsition.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'shop/vendor/bootstrap-progressbar/bootstrap-progressbar-3.3.4.min.css' %}" rel="stylesheet"
        media="all">
    <link href="{% static 'shop/vendor/wow/animate.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'shop/vendor/css-hamburgers/hamburgers.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'shop/vendor/slick/slick.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'shop/vendor/select2/select2.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'shop/vendor/perfect-scrollbar/perfect-scrollbar.css' %}" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="{% static 'shop/css/theme.css' %}" rel="stylesheet" media="all">

</head>

<body class="animsition">
    <div class="page-wrapper">
        {% include "store/layout/header_mobile.html" %}
        {% include "store/layout/menu_sidebar.html" %}
        <div class="page-container">
            <div class="main-content">
                {% include "store/layout/header_desktop.html" %}
                {% block content %}

                {% endblock content %}
            </div>


        </div>
    </div>

    {% include "store/layout/script.html" %}


</body>

</html>

templates/base_test.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <!-- Title  -->
    <title>Amado - Furniture Ecommerce Template | Shop</title>

    <!-- Favicon  -->
    <link rel="icon" href="{% static 'user/img/core-img/favicon.ico'%}">

    <!-- Core Style CSS -->
    <link rel="stylesheet" href="{% static 'user/css/core-style.css'%}">
    <link rel="stylesheet" href="{% static 'user/style.css'%}">

</head>

<body>
    {% block content  %}
    {% endblock content %}

    <!-- ##### Newsletter Area Start ##### -->
    <section class="newsletter-area section-padding-100-0">
        <div class="container">
            <div class="row align-items-center">
                <!-- Newsletter Text -->
                <div class="col-12 col-lg-6 col-xl-7">
                    <div class="newsletter-text mb-100">
                        <h2>Subscribe for a <span>25% Discount</span></h2>
                        <p>Nulla ac convallis lorem, eget euismod nisl. Donec in libero sit amet mi
                            vulputate
                            consectetur. Donec auctor interdum purus, ac finibus massa bibendum nec.</p>
                    </div>
                </div>
                <!-- Newsletter Form -->
                <div class="col-12 col-lg-6 col-xl-5">
                    <div class="newsletter-form mb-100">
                        <form action="#" method="post">
                            <input type="email" name="email" class="nl-email" placeholder="Your E-mail">
                            <input type="submit" value="Subscribe">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- ##### Newsletter Area End ##### -->

    <!-- ##### Footer Area Start ##### -->
    <footer class="footer_area clearfix">
        <div class="container">
            <div class="row align-items-center">
                <!-- Single Widget Area -->
                <div class="col-12 col-lg-4">
                    <div class="single_widget_area">
                        <!-- Logo -->
                        <div class="footer-logo mr-50">
                            <a href="index.html"><img src="{% static 'user/img/core-img/logo2.png'%}" alt=""></a>
                        </div>
                        <!-- Copywrite Text -->
                        <p class="copywrite">
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            Copyright &copy;
                            <script>document.write(new Date().getFullYear());</script> All rights
                            reserved | This
                            template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a
                                href="https://colorlib.com" target="_blank">Colorlib</a>
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    </div>
                </div>
                <!-- Single Widget Area -->
                <div class="col-12 col-lg-8">
                    <div class="single_widget_area">
                        <!-- Footer Menu -->
                        <div class="footer_menu">
                            <nav class="navbar navbar-expand-lg justify-content-end">
                                <button class="navbar-toggler" type="button" data-toggle="collapse"
                                    data-target="#footerNavContent" aria-controls="footerNavContent"
                                    aria-expanded="false" aria-label="Toggle navigation"><i
                                        class="fa fa-bars"></i></button>
                                <div class="collapse navbar-collapse" id="footerNavContent">
                                    <ul class="navbar-nav ml-auto">
                                        <li class="nav-item active">
                                            <a class="nav-link" href="index.html">Home</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="shop.html">Shop</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="product-details.html">Product</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="cart.html">Cart</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="checkout.html">Checkout</a>
                                        </li>
                                    </ul>
                                </div>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- ##### Footer Area End ##### -->


    <!-- ##### jQuery (Necessary for All JavaScript Plugins) ##### -->
    <script src="{% static 'user/js/jquery/jquery-2.2.4.min.js' %}"></script>
    <!-- Popper js -->
    <script src="{% static 'user/js/popper.min.js' %}"></script>
    <!-- Bootstrap js -->
    <script src="{% static 'user/js/bootstrap.min.js' %}"></script>
    <!-- Plugins js -->
    <script src="{% static 'user/js/plugins.js' %}"></script>
    <!-- Active js -->
    <script src="{% static 'user/js/active.js'%}"></script>

</body>

</html>

templates/checkout.html
{% extends 'base.html'%}
{%load static %}
{% block content %}
<!-- ##### Main Content Wrapper Start ##### -->
<div class="main-content-wrapper d-flex clearfix">

    {% include "layouts/mobile.html"%}
    {% include "layouts/sidebar.html"%}




    <div class="cart-table-area section-padding-100">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12 col-lg-8">
                    <div class="checkout_details_area mt-50 clearfix">

                        <div class="cart-title">
                            <h2>Checkout</h2>
                        </div>

                        <form action="#" method="post">
                            <div class="row">
                                <div class="col-md-6 mb-3">
                                    <input type="text" class="form-control" id="first_name" value=""
                                        placeholder="First Name" required>
                                </div>
                                <div class="col-md-6 mb-3">
                                    <input type="text" class="form-control" id="last_name" value=""
                                        placeholder="Last Name" required>
                                </div>
                                <div class="col-12 mb-3">
                                    <input type="text" class="form-control" id="company" placeholder="Company Name"
                                        value="">
                                </div>
                                <div class="col-12 mb-3">
                                    <input type="email" class="form-control" id="email" placeholder="Email" value="">
                                </div>

                                <div class="col-12 mb-3">
                                    <input type="text" class="form-control mb-3" id="street_address"
                                        placeholder="Address" value="">
                                </div>
                                <div class="col-12 mb-3">
                                    <input type="text" class="form-control" id="city" placeholder="Town" value="">
                                </div>
                                <div class="col-md-6 mb-3">
                                    <input type="text" class="form-control" id="zipCode" placeholder="Zip Code"
                                        value="">
                                </div>
                                <div class="col-md-6 mb-3">
                                    <input type="number" class="form-control" id="phone_number" min="0"
                                        placeholder="Phone No" value="">
                                </div>
                                <div class="col-12 mb-3">
                                    <textarea name="comment" class="form-control w-100" id="comment" cols="30" rows="10"
                                        placeholder="Leave a comment about your order"></textarea>
                                </div>

                                <div class="col-12">
                                    <div class="custom-control custom-checkbox d-block mb-2">
                                        <input type="checkbox" class="custom-control-input" id="customCheck2">
                                        <label class="custom-control-label" for="customCheck2">Create an accout</label>
                                    </div>
                                    <div class="custom-control custom-checkbox d-block">
                                        <input type="checkbox" class="custom-control-input" id="customCheck3">
                                        <label class="custom-control-label" for="customCheck3">Ship to a different
                                            address</label>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="col-12 col-lg-4">
                    <div class="cart-summary">
                        <h5>Cart Total</h5>
                        <ul class="summary-table">
                            <li><span>subtotal:</span> <span>$140.00</span></li>
                            <li><span>delivery:</span> <span>Free</span></li>
                            <li><span>total:</span> <span>$140.00</span></li>
                        </ul>

                        <div class="payment-method">
                            <!-- Cash on delivery -->
                            <div class="custom-control custom-checkbox mr-sm-2">
                                <input type="checkbox" class="custom-control-input" id="cod" checked>
                                <label class="custom-control-label" for="cod">Cash on Delivery</label>
                            </div>
                            <!-- Paypal -->
                            <div class="custom-control custom-checkbox mr-sm-2">
                                <input type="checkbox" class="custom-control-input" id="paypal">
                                <label class="custom-control-label" for="paypal">Paypal <img class="ml-15"
                                        src="img/core-img/paypal.png" alt=""></label>
                            </div>
                        </div>

                        <div class="cart-btn mt-100">
                            <a href="#" class="btn amado-btn w-100">Checkout</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- ##### Main Content Wrapper End ##### -->
{% endblock content %}

templates/customer_order.html
{% extends "base1.html" %}

{% block content1 %}
<main>
    <div class="container">


        <!--/.Navbar-->

        <!--Section: Products v.3-->
        <section class="text-center mb-4">

            <div class="row wow fadeIn">

                {% for item in object %}
                <div class="col-lg-3 col-md-6 mb-4">

                    <div class="card">



                        <div class="card-body text-center">
                            <a href="" class="grey-text">

                                <p> Pochondoo Orderd ID: {{ item.id}}</p>

                                {% if item.ordered %}
                                Orderd
                                {% else %}
                                Not Orderd
                                {% endif %}



                            </a>


                            <h4 class="font-weight-bold blue-text">
                                <strong>
                                    <p class="lead">
                                        Total Amount: {{ item.get_total }} BDT
                                    </p>
                                </strong>
                            </h4>

                        </div>

                    </div>

                </div>
                {% endfor %}
            </div>

        </section>
        <!--Section: Products v.3-->

        <!--Pagination-->



    </div>
</main>

{% endblock content1 %}

templates/footer.html
{% load static %}
<footer>

    <hr class="my-4">


    <!-- Social icons -->
    <div class="footer-copyright py-3">
        আপনার বিজনেসটি রেজিস্ট্রেশন করতে যোগাযোগ করুন
        <a href="#" target="_blank"> 01950641081 </a>
    </div>
    <!--Copyright-->
    <div class="footer-copyright py-3">
        © 2020 Copyright:
        <a href="#" target="_blank"> LinB1 </a>
    </div>
    <!--/.Copyright-->

</footer>
<!-- ##### Footer Area End ##### -->

templates/order_snippet.html
<div class="col-md-12 mb-4">
    <h4 class="d-flex justify-content-between align-items-center mb-3">
        <span class="text-muted">Your cart</span>
        <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
    </h4>
    <ul class="list-group mb-3 z-depth-1">
        {% for order_item in order.items.all %}
        <li class="list-group-item d-flex justify-content-between lh-condensed">
            <div>
                <h6 class="my-0">{{ order_item.quantity }} x {{ order_item.item.title}}</h6>
                <small class="text-muted">{{ order_item.item.description}}</small>
            </div>
            <span class="text-muted">BDT{{ order_item.get_final_price }}</span>
        </li>
        {% endfor %}
        {% if order.coupon %}
        <li class="list-group-item d-flex justify-content-between bg-light">
            <div class="text-success">
                <h6 class="my-0">Promo code</h6>
                <small>{{ order.coupon.code }}</small>
            </div>
            <span class="text-success">-BDT{{ order.coupon.amount }}</span>
        </li>
        {% endif %}
        <li class="list-group-item d-flex justify-content-between">
            <span>Total (USD)</span>
            <strong>BDT{{ order.get_total }}</strong>
        </li>
    </ul>

    {% if DISPLAY_COUPON_FORM %}
    <form class="card p-2" action="{% url 'core:add-coupon' %}" method="POST">
        {% csrf_token %}
        <div class="input-group">
            {{ couponform.code }}
            <div class="input-group-append">
                <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Redeem</button>
            </div>
        </div>
    </form>
    {% endif %}

</div>

templates/order_summary.html
{% extends "base1.html" %}

{% block content1 %}
<main>
    <div class="container">

        <div class="table-responsive text-nowrap">
            <h2>Order Summary</h2>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Item title</th>
                        <th scope="col">Price</th>
                        <th scope="col">Quantity</th>
                        <th scope="col">Total Item Price</th>
                    </tr>
                </thead>
                <tbody>
                    {% for order_item in object.items.all %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ order_item.item.title }}</td>
                        <td>{{ order_item.item.price }}</td>
                        <td>
                            <a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}"><i
                                    class="fas fa-minus mr-2"></i></a>
                            {{ order_item.quantity }}
                            <a href="{% url 'core:add-to-cart' order_item.item.slug %}"><i
                                    class="fas fa-plus ml-2"></i></a>
                        </td>
                        <td>
                            {% if order_item.item.discount_price %}
                            BDT{{ order_item.get_total_discount_item_price }}
                            <span class="badge badge-primary">Saving BDT{{ order_item.get_amount_saved }}</span>
                            {% else %}
                            BDT{{ order_item.get_total_item_price }}
                            {% endif %}
                            <a style='color: red;' href="{% url 'core:remove-from-cart' order_item.item.slug %}">
                                <i class="fas fa-trash float-right"></i>
                            </a>
                        </td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan='5'>Your cart is empty</td>
                    </tr>
                    <tr>
                        <td colspan="5">
                            <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
                        </td>
                    </tr>
                    {% endfor %}
                    {% if object.coupon %}
                    <tr>
                        <td colspan="4"><b>Coupon</b></td>
                        <td><b>-BDT{{ object.coupon.amount }}</b></td>
                    </tr>
                    {% endif %}
                    {% if object.get_total %}
                    <tr>
                        <td colspan="4"><b>Order Total</b></td>
                        <td><b>BDT{{ object.get_total }}</b></td>
                    </tr>
                    <tr>
                        <td colspan="5">
                            <a class='btn btn-warning float-right ml-2' href='/checkout/'>Proceed to checkout</a>
                            <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
                        </td>
                    </tr>
                    {% endif %}
                </tbody>
            </table>

        </div>

    </div>
</main>

{% endblock content1 %}

templates/request_refund.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <main>
    <div class="container">

    <h2>Request Refund</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class='btn btn-primary'>Submit</button>
    </form>

    </div>
  </main>

{% endblock content %}

templates/scripts.html
{% load static %}

<!-- ##### jQuery (Necessary for All JavaScript Plugins) ##### -->
<script src="{% static 'user/js/jquery/jquery-2.2.4.min.js' %}"></script>
<!-- Popper js -->
<script src="{% static 'user/js/popper.min.js' %}"></script>
<!-- Bootstrap js -->
<script src="{% static 'user/js/bootstrap.min.js' %}"></script>
<!-- Plugins js -->
<script src="{% static 'user/js/plugins.js' %}"></script>
<!-- Active js -->
<script src="{% static 'user/js/active.js'%}"></script>

templates/shops.html
{% extends "base.html" %}

{% block title %}
Pochonder Sob
{% endblock %}
{% block content %}

<!-- ##### Main Content Wrapper Start ##### -->
<div class="main-content-wrapper d-flex clearfix">

    {% include "layouts/mobile.html"%}
    {% include "layouts/sidebar.html"%}
    {% include "layouts/search.html"%}
    <!-- Product Catagories/store/Service Area Area Start -->
    <div class="products-catagories-area clearfix">
        <div class="amado-pro-catagory clearfix">

            {% include "items/shop.html" %}

        </div>
    </div>
    <!-- Product Catagories/store/Service Area End -->
</div>
<!-- ##### Main Content Wrapper End ##### -->

{% endblock content %}