core/urls.py
from django.urls import path
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import url

from django.views.static import serve

from .views import (
    ItemDetailView,
    CheckoutView,
    # HomeView,
    OrderSummaryView,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
    # PaymentView,
    AddCouponView,
    ShopCreate,
    MarketsView,
    ShopsView,
    ProductsView,
    get_items,
    # RequestRefundView,
    add_item, add_shop,
    CustomerOrderStatusView,
    get_shop_cat_items,
    home_view,
    side_bar,
    get_shops,

)
app_name = 'core'

urlpatterns = [
    # path('all', HomeView.as_view(), name='home'),
    # path('', ShopsView.as_view(), name='shops'),
    # path('', home_view, name='home'),
    path('', MarketsView.as_view(), name='markets'),
    path('markets/', MarketsView.as_view(), name='markets'),
    path('shops/', ShopsView.as_view(), name='shops'),
    path('products/', ProductsView.as_view(), name='products'),

    path('shop-items/<id>/', get_items, name='shop-items'),
    path('area/<id>/', get_shops, name='area-shops'),
    path('shops-cat/<id>', get_shop_cat_items,
         name='shops-cat'),
    path('offer-shop/<id>', get_shop_cat_items,
         name='shops-offer'),

    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('shop/add/', ShopCreate.as_view(), name='add-shop'),
    path('order/', CustomerOrderStatusView.as_view(), name='customer-order'),

    # path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    # path('request-refund/', RequestRefundView.as_view(), name='request-refund'),
    url(r'^uploads/simple/$', add_shop, name='add_shop'),
    url(r'^uploads/form/$', add_item, name='add_item'),
    url(r'^image/(?P<path>.*)$', serve,
        {'document_root': settings.MEDIA_ROOT}),

    url(r'^static/(?P<path>.*)$', serve,
        {'document_root': settings.STATIC_ROOT}),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/a/layout/footer.html
{% load static %}
<!-- ##### Footer Area Start ##### -->
<footer class="footer_area clearfix">

    <h1 style="color: whitesmoke; text-align: center;">


        খুলনা শহর জুড়ে মাত্র ১ ঘন্টায় ডেলিভারি!!

        <p> পছন্দের-সব.কম || <a>


                <span> পছন্দের সব । পছন্দই সব </span></a>
        </p>

    </h1>
    <!-- Single Widget Area -->

    <!-- Single Widget Area 
            <div class="col-12 col-lg-4">
                <div class="single_widget_area">

                    -->
    <!-- Footer Menu 
                    <div class="footer_menu">
                        <nav class="navbar navbar-expand-lg justify-content-end">
                            <button class="navbar-toggler" type="button" data-toggle="collapse"
                                data-target="#footerNavContent" aria-controls="footerNavContent" aria-expanded="false"
                                aria-label="Toggle navigation"><i class="fa fa-bars"></i></button>
                            <div class="collapse navbar-collapse" id="footerNavContent">
                                <ul class="navbar-nav ml-auto">
                                    <li class="nav-item active">
                                        <a class="nav-link" href="/">খুলনা শহর জুড়ে মাত্র ১ ঘন্টায় ডেলিভারি
                                            !!</a>
                                    </li>

                                </ul>
                            </div>
                        </nav>
                    </div>


        </div>
    </div>
    -->


</footer>

templates/a/layout/header.html
{% load static %}
{% load cart_template_tags %}
<!-- Header Area Start -->
<header class="header-area clearfix">
    <!-- Close Icon -->
    <div class="nav-close">
        <i class="fa fa-close" aria-hidden="true"></i>
    </div>
    <!-- Logo -->
    <div class="logo">
        <a href="/"><img src="{% static 'amado/img/core-img/logo.jpg' %}" alt=""></a>
    </div>
    <!-- Amado Nav -->
    <nav class="amado-nav">
        <ul>

            <li><a href="/">Home</a></li>

            <!--
                <li class="active"><a href="shop.html">Search</a></li>
            -->

            <li><a href="{% url 'core:markets' %}">Market</a></li>
            <li><a href="{% url 'core:shops' %}">Shop</a></li>
            <li><a href="{% url 'core:products' %}">Product</a></li>

            {% if request.user.is_authenticated %}
            <li>
                <a href="{% url 'core:order-summary' %}" class="cart-nav"><img
                        src="{% static 'amado/img/core-img/cart.png' %}" alt=""> Cart
                    <span>({{ request.user|cart_item_count }}) </span></a>
            </li>
            <li>
                <a href="{% url 'core:customer-order' %}">

                    My Orders </a>
                </a>
            </li>
            <li>
                <a class="nav-link waves-effect" href="{% url 'account_logout' %}"> Logout
                </a>
            </li>
            {% else %}

            <li>
                <a href="{% url 'account_login' %}">
                    Login
                </a>
            </li>
            <li>
                <a href="{% url 'account_signup' %}">
                    Signup </span>
                </a>
            </li>
            {% endif %}

        </ul>
    </nav>

    {% if request.user.is_authenticated %}

    <p>
        <span class=""> Hello {{ request.user.username }}! </span>

    </p>

    {% endif %}
</header>
<!-- Header Area End -->

templates/a/layout/mobile_nav.html
{% load static %}
<div class="mobile-nav">
    <!-- Navbar Brand -->
    <div class="amado-navbar-brand">
        <a href="index.html"><img src="{% static 'amado/img/core-img/logo.png' %}" alt=""></a>
    </div>
    <!-- Navbar Toggler -->
    <div class="amado-navbar-toggler">
        <span></span><span></span><span></span>
    </div>
</div>

templates/a/layout/script.html
{% load static %}
<!-- ##### jQuery (Necessary for All JavaScript Plugins) ##### -->
<script src="{% static 'amado/js/jquery/jquery-2.2.4.min.js' %}"></script>
<!-- Popper js -->
<script src="{% static 'amado/js/popper.min.js' %}"></script>
<!-- Bootstrap js -->
<script src="{% static 'amado/js/bootstrap.min.js' %}"></script>
<!-- Plugins js -->
<script src="{% static 'amado/js/plugins.js' %}"></script>
<!-- Active js -->
<script src="{% static 'amado/js/active.js' %}"></script>

templates/a/layout/search.html
{% load static %}
<div class="search-wrapper section-padding-100">
    <div class="search-close">
        <i class="fa fa-close" aria-hidden="true"></i>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="search-content">
                    <form action="#" method="get">
                        <input type="search" name="search" id="search" placeholder="Type your keyword...">
                        <button type="submit"><img src="{% static 'amado/img/core-img/search.png' %}" alt=""></button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

templates/a/layout/sidebar1.html
{% load static %}
<div class="shop_sidebar_area">

    <!-- ##### Single Widget ##### -->
    <div class="widget catagory mb-50">
        <!-- Widget Title -->
        <h6 class="widget-title mb-30">Catagories</h6>

        <!--  Catagories  -->
        <div class="catagories-menu">
            <ul>
                {% for item in cats %}
                <li><a href="#">{{item}}</a></li>
                {% endfor %}
                <!--
                <li class="active"><a href="#">Chairs</a></li>
                <li><a href="#">Beds</a></li>
                <li><a href="#">Accesories</a></li>
                <li><a href="#">Furniture</a></li>
                <li><a href="#">Home Deco</a></li>
                <li><a href="#">Dressings</a></li>
                <li><a href="#">Tables</a></li>
                -->

            </ul>
        </div>
    </div>

    <!-- Side Start -->
    <div class="widget catagory mb-50">
        <!-- Widget Title -->
        <h6 class="widget-title mb-30">Markets</h6>

        <!--  Market -->
        <div class="catagories-menu">
            <ul>
                {% for item in markets %}
                <li><a href="#">{{item}}</a></li>
                {% endfor %}

            </ul>
        </div>
    </div>
    <!-- Side End -->

    <!-- Side Start -->
    <div class="widget catagory mb-50">
        <!-- Widget Title -->
        <h6 class="widget-title mb-30">Shops</h6>

        <!--  Shops -->
        <div class="catagories-menu">
            <ul>
                {% for item in shops %}
                <li><a href="#">{{item}}</a></li>
                {% endfor %}

            </ul>
        </div>
    </div>
    <!-- Side End -->









</div>